name: zooper_flutter_core
description: The core package of the whole zooper library
version: 1.0.3
homepage: https://github.com/zooper-lib/

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:

  intl: ^0.20.2

  # Used for extensions on DateTime
  jiffy: ^6.4.4

  json_annotation: ^4.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6