name: zooper_flutter_core
description: The core package of the whole zooper library
version: 0.0.2
homepage: https://github.com/DirtyNative/Zooper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

  # Used for extensions on DateTime
  jiffy: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  
flutter:
